config:
    rolls: 25
    
    ERThreshold?: true #Will distribute rolls to achieve the set threshold
    ERThreshold: 1.2 #150% = 1.5
    
    
    EMReactionMultiplier: 1.5 #1.5 for reverse melt/vape, 2 for melt/vape
    ReactionRatio: 0.0 #0 for no reactions
    ReactionBonus: 0.15 #like 4p CW set bonus

character: 
    ATK: 349
    HP: 12736
    DEF: 799
    
    ATKPercent: 0.0
    HPPercent: 0.0
    DEFPercent: 0.0
    
    CritRate: 0.242
    CritDMG: 0.5
    EM: 0
    EnergyRecharge: 1.0
    
weapon: 
    ATK: 674
    HP: 0
    DEF: 0
    
    ATKPercent: 0.224
    HPPercent: 0.0
    DEFPercent: 0.0
    
    CritRate: 0.2205
    CritDMG: 0.0
    EM: 0
    EnergyRecharge: 0.0

buffs:
    FlatATK: 1000 #you can put bennett's buff here

artifactMainStatChoice: #copy the names from artifactMainStats
    sands: ATKPercent
    goblet: AnemoDMG
    circlet: CritDMG
    
    
artifactMainStats: #leave these two untouched
    HP: 4780
    HPPercent: 0.4659999907
    ATK: 311
    ATKPercent: 0.4659999907
    DEFPercent: 0.5830000043
    CritRate: 0.3109999895
    CritDMG: 0.621999979
    EnergyRecharge: 0.5180000067
    HealingBonus: 0.3589999974
    EM: 186.5
    AnemoDMG: 0.4659999907
    GeoDMG: 0.4659999907
    ElectroDMG: 0.4659999907
    HydroDMG: 0.4659999907
    PyroDMG: 0.4659999907
    CryoDMG: 0.4659999907
    PhysicalDMG: 0.5830000043
    
artifactSubStatRolls:
    ATKPercent: 0.0582999996840954
    CritRate: 0.0388999991118908
    CritDMG: 0.0776999965310097
    EnergyRecharge: 0.064800001680851
    EM: 23.3099994659424